[project]
name = "lse-diss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.1",
    "httpx>=0.28.1",
    "polars>=1.26.0",
    "sentence-transformers>=3.3.1",
    "tqdm>=4.67.0",
    "voyager>=2.1.0",
]
