default:
  patents:
    q:
      _and:
        - _gte:
            patent_date: '2023-01-01'
        - _lte:
            patent_date: '2024-01-01'
        - _eq:
            assignees.assignee_type: '2'
        - _eq:
            assignees.assignee_country: US
        - _eq:
            patent_type: utility
        - _eq:
            inventors.inventor_country: US
    f:
      - patent_id
      - patent_date
      - patent_abstract
      - patent_num_times_cited_by_us_patents
      - inventors
      - assignees
    s:
      - patent_id: asc
    o:
      size: null
  us_patent_citations:
    q:
      citation_patent_id: null
    f:
      - patent_id
      - citation_patent_id
      - citation_category
    s:
      - citation_patent_id: asc
    o:
      size: null
  inventors:
    q:
      inventor_id: null
    f:
      - inventor_id
      - inventor_lastknown_location
    s:
      - inventor_id: asc
    o:
      size: null
  locations:
    q:
      location_id: null
    f:
      - location_id
      - location_latitude
      - location_longitude
    s:
      - location_id: asc
    o:
      size: null
production: null