default:
  patents:
    q:
      _and:
        - _gte:
            patent_date: '2023-01-01'
        - _lte:
            patent_date: '2024-01-01'
        - _eq:
            assignees.assignee_type: '2'
        - _eq:
            assignees.assignee_country: US
        - _eq:
            patent_type: utility
        - _eq:
            inventors.inventor_country: us
    f:
      - patent_id
      - patent_date
      - patent_abstract
      - patent_num_times_cited_by_us_patents
      - inventors
      - assignees
    s:
      - patent_id: asc
    o:
      size: 5
production: null
