---
title: "Title Here"
format: typst
---

## Abstract

Abstract Text

## Introduction

Literature review? I should probably motivate the paper here.

There are two key aspects that need to be considered. The previous papers and the methodological criticism.

Then, I might want to explain

## Conceptual framework

## Data

How I constructed the sample.

Summary Statistics

## Empirical strategy

I would like to delineate what kind of causal effect I could be estimating here, but it seems somewhat difficult.

Is it that the structural equation captures the effect of proximity on a paper existing? Then is citation a proxy for it?

I am starting to think about the control patents as some sort of matching. Then, these should proxy for controlling for a bunch of different things, right? And the matching variable here is text, so how could this proxy for unobservables like density of ideas in an area.

So something like this:

1. We believe that patents might cluster for two different reasons: either they learn from patents near them (or from the people making these patents), or they reflect other underlying economic incentives.
2. The other economic incentives could be generally understood as agglomeration, so why would these inventors agglomerate? because their employers do. However, agglomeration might be driven by these spillovers.
3. As such, we can really divide it in three aspects: direct effects (peer effects?), indirect effects (through agglomeration), other agglomeration effects.
4. What might other agglomeration effects be? Physical constraints (e.g., industry bcs where natural resources are).

So if we control for pre-existing industry characteristics, any additional effects will be direct immediate effects.

Do we observe what these other forces directly? No, but we believe the content of the patent is a good proxy for all these characteristics. Since its too complicated to regress on some specification for this proxy, we do perfect matching based on the embedding.

I am also very confused about how citing vs. non citing is with respect to some form of independence.

I think I can use typst math rather than latex one.

```{=typst}
$ A = pi r^2 $
```

## Results

## Conclusion
